### ISSUE TITLE
Vesktop 1.5.1 soft locks when trying to start a stream

### ISSUE THREAD

**Issue by Keheck** [Vencord/venmic#18] opened 2024-03-13 17:13 UTC
**Describe the bug**

When trying to stream an application or monitor, the client soft locks after selecting the application or monitor, hanging at "Loading Audio Sources...". Voice Chatting is still possible and the client still animates everything properly, but no longer responds to user input. The desktop environment eventually reports that Vesktop is no longer responding.

**To Reproduce**

1. Join a Voice Chat
2. Click the button to stream
3. Select a video source

**Expected behavior**

Expected the client to not crash and instead load everything properly

**Screenshots**

![Example](https://github.com/Vencord/Vesktop/assets/42344102/bda33a90-42c2-42cf-8e61-6b1eb3ef82b6)

**Desktop (please complete the following information):**
 - OS/Distro: Linux Mint
 - Desktop Environment (linux only): Gnome
 - Version: Cinnamon 21.3 (Kernel 5.15.0-100-generic)

**Command line output**

```
[2024-03-13 18:08:06.592] [venmic] [info] [patchbay] (get) running venmic 3.3.2
```
This is the only output that I get
EDIT: I tried to run with `VENMIC_ENABE_LOG` set as an environment variable (as suggested in the README), this is what it produced. It doesn't seem that useful to my untrained eye, but maybe there is something there that'll help
```
[2024-03-18 16:00:18.385] [venmic] [debug] [patchbay] (has_pipewire) pulse-server is "pulseaudio (on pipewire 0.3.48)"
[2024-03-18 16:00:18.388] [venmic] [info] [patchbay] (get) running venmic 3.3.2
[2024-03-18 16:00:18.388] [venmic] [trace] [patchbay] (has_pipewire) using cached result
```

**Additional context**

~~I have updated to 1.5.1 today, but haven't streamed in a bit so I can't say for sure that updating the app is what caused the issue, but this was the first time this has happened to me~~
UPDATE: I have just confirmed that the issue is definitely the jump from 1.5.0 to 1.5.1 or something associated with it

**Comment by gott04york** [comment] 2024-03-20 23:05
Can confirm as well, on Debian 12, KDE wayland. Pipewire running through pulseaudio.
Running `pactl info | grep "Server Name"` gives me `Server Name: PulseAudio (on PipeWire 0.3.65)` so maybe it might be that

**Comment by ranidspace** [comment] 2024-03-20 23:07
Can confirm this on 1.5.1 as well, on Debian 12, KDE wayland.

Running pactl info | grep "Server Name" gives me Server Name: PulseAudio (on PipeWire 0.3.65) so maybe it might be that

**Comment by wayhoi** [comment] 2024-03-28 13:24
Hello. I have the same problem, when starting screen share after changing pulseaudio to pipewire freezes the client.

![Screenshot from 2024-03-27 16-25-53](https://github.com/Vencord/Vesktop/assets/163326927/93ce0f57-bbe6-4b23-9708-639b0aa724fd)

```
             ...-:::::-...                 pc
          .-MMMMMMMMMMMMMMM-.              -------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 21.3 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: Adder WS addw3 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 6.6.10-76060610-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 1 day, 26 mins 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 2303 (dpkg), 21 (flatpak) 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: zsh 5.8.1 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 1920x1080 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   DE: Cinnamon 6.0.4 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   WM: Mutter (Muffin) 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   WM Theme: Mint-Y-Dark-Orange (Mint-Y) 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Theme: Mint-Y-Dark-Orange [GTK2/3] 
  :MMM:MMM:`                `:MMM:MMM:     Icons: Mint-Y-Yaru [GTK2/3] 
   .MMM.MMMM:--------------:MMMM.MMM.      Terminal: gnome-terminal 
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'       CPU: 13th Gen Intel i9-13900HX (32) @ 5. 
       '.-MMMM``--:::::--``MMMM-.'         GPU: NVIDIA 01:00.0 NVIDIA Corporation D 
            '-MMMMMMMMMMMMM-'              GPU: Intel Device a788 
               ``-:::::-``                 Memory: 10362MiB / 31936MiB
```

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 426
Tile Size: 65472
User Name: sedyh
Host Name: sedyh-pc
Server Name: PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1f.3.analog-stereo
Default Source: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: dca1:1bd6
```

```
/opt/Vesktop/vesktop
[8698:0327/163219.611204:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
[2024-03-27 16:32:31.380] [venmic] [info] [patchbay] (get) running venmic 3.3.2
```

**Comment by Curve** [comment] 2024-03-30 21:40
Please also attach the detailed log, see the [readme](https://github.com/Vencord/venmic) under debugging

**Comment by Curve** [comment] 2024-03-30 21:46
> UPDATE: I have just confirmed that the issue is definitely the jump from 1.5.0 to 1.5.1 or something associated with it

Will do a bisect from 3.2.3 to 3.3.2 to see what could cause the issue.

**Comment by Curve** [comment] 2024-03-30 23:27
I think the problem may be [this change](https://github.com/Curve/rohrkabel/compare/v2.5...v3.0#diff-152d5d491bb86493dcc369469b93fb5f66b00d544f2021b3c3be0843e8201093R83) introduced in `rohrkabel`.

What it does is move from the `pw_proxy_events::bound_props` instead of `pw_proxy_events::bound`. The new event was only introduced in [pipewire 0.3.68](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.68) though, which probably leads to it never getting fired on earlier pipewire versions (`0.3.48` in this case).

I will see if I can add back support for older pipewire versions.

**Comment by Curve** [comment] 2024-03-31 13:46
> Should be fixed in [v3.3.3](https://github.com/Vencord/venmic/releases/tag/v3.3.3)

Could anyone affected by the issue manually bump venmic in Vesktop to `3.3.3` and see if that fixes it?

**Comment by tempname1024** [comment] 2024-03-31 15:24
> > Should be fixed in [v3.3.3](https://github.com/Vencord/venmic/releases/tag/v3.3.3)
> 
> Could anyone affected by the issue manually bump venmic in Vesktop to `3.3.3` and see if that fixes it?

The issue is fixed in venmic 3.3.3, thanks so much!

**Comment by Curve** [comment] 2024-03-31 15:30
> > > Should be fixed in [v3.3.3](https://github.com/Vencord/venmic/releases/tag/v3.3.3)
> > 
> > Could anyone affected by the issue manually bump venmic in Vesktop to `3.3.3` and see if that fixes it?
> 
> The issue is fixed in venmic 3.3.3, thanks so much!

Thanks for confirming! 

@Vendicated could you bump venmic in vesktop?

**Closed by Curve** 2024-03-31 15:30 UTC
Labels: bug, cant-reproduce

**Comment by wayhoi** [comment] 2024-04-04 15:12
Hmm, I guess its not in vesktop at the moment? 
Where can I check the status? Can I apply that fix manually to check on my pc?

**Comment by Curve** [comment] 2024-04-04 15:14
> Hmm, I guess its not in vesktop at the moment? 
> Where can I check the status? Can I apply that fix manually to check on my pc?

No it's not in Desktop yet, you can however clone the vesktop repository and bump Venmic in the `package.json` to `3.3.3`.

Thanks for mentioning, I still need to submit a PR for the update ^^

**Comment by cloudskater** [comment] 2024-05-28 21:54
> > Hmm, I guess its not in vesktop at the moment?
> > Where can I check the status? Can I apply that fix manually to check on my pc?
> 
> No it's not in Vesktop yet, you can however clone the vesktop repository and bump Venmic in the `package.json` to `3.3.3`.
> 
> Thanks for mentioning, I still need to submit a PR for the update ^^

Hey, could you inform me where that json file is to "bump" it? I only just switched to Linux Mint yesterday and I've been trying to fix this issue for hours yet can't find this one file I seemingly need to correct or change. Please let me know how I can correct package.json.

**Comment by Curve** [comment] 2024-05-28 22:02
> > > Hmm, I guess its not in vesktop at the moment?
> > > Where can I check the status? Can I apply that fix manually to check on my pc?
> > 
> > No it's not in Vesktop yet, you can however clone the vesktop repository and bump Venmic in the `package.json` to `3.3.3`.
> > 
> > Thanks for mentioning, I still need to submit a PR for the update ^^
> 
> Hey, could you inform me where that json file is to "bump" it? I only just switched to Linux Mint yesterday and I've been trying to fix this issue for hours yet can't find this one file I seemingly need to correct or change. Please let me know how I can correct package.json.

You can also switch to pipewire, then you'll actually be able to share audio - pulse does not support this yet

**Comment by Vendicated** [comment] 2024-05-28 22:04
https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e?permalink_comment_id=3976215#install

**Comment by pepperonipizzah** [comment] 2024-06-13 18:02
can someone say explicitly where it is that i can bump venmic to 3.3.3?

**Comment by Curve** [comment] 2024-06-14 15:53
> can someone say explicitly where it is that i can bump venmic to 3.3.3?

Try building #621 ([this](https://github.com/Curve/Vesktop/tree/venmic-expert) tree), it has venmic bumped to the latest version.

**Comment by pepperonipizzah** [comment] 2024-06-15 12:53
ill see if i can do it later if i have time

when will this be in the official build?

**Comment by Curve** [comment] 2024-06-15 13:11
> when will this be in the official build?

As soon as the PR is merged.

**Comment by pepperonipizzah** [comment] 2024-06-16 16:22
I cant say for sure, but I am nearly certain it is caused by not owning discord nitro, the default vencord screensharing option is 1920x1080@60 but if you manage to change it to 720@30 (before it crashes) it seems to work.

**Comment by Curve** [comment] 2024-06-16 16:24
> I cant say for sure, but I am nearly certain it is caused by not owning discord nitro, the default vencord screensharing option is 1920x1080@60 but if you manage to change it to 720@30 (before it crashes) it seems to work.

This most certainly related to audio share and not the video quality. #621 is merged now so you might as well try latest git to see if it fixes the issue for you.

**Comment by jzupko** [comment] 2024-06-17 23:39
Note (and maybe this should be a separate issue?) - on a Linux Mint 21.3 distro, I still ran into this soft lock on Vesktop 1.5.2 until I updated my distro to use PipeWire. Prior to those versions, the capture screen would display a user friendly error about needing PipeWire. In 1.5.1 and 1.5.2, it soft locks instead.

**Comment by Vendicated** [comment] 2024-06-17 23:43
known. will be fixed in next release (is already fixed on master)

**Comment by KweezyCode** [comment] 2024-08-07 13:13
is there any fix? i can still reproduce issue with the latest flatpak version

**Comment by TheBloodyScreen** [comment] 2024-08-08 21:09
This issue indeed still occurs for me too on v 1.5.3 flatpak.

**Comment by nefarius** [comment] 2025-08-27 13:40
To those *still* affected; make sure you run pipwire as the default audio server, not pulseaudio:
```bash
pactl info | grep "Server Name"
```
should give you something similar to:
```
Server Name: PulseAudio (on PipeWire 0.3.48)
```
It is overall safe and easy to switch from pulse to pipewire on latest Linux Mint, just lookup a guide.
